name: Linux Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Test
      shell: bash
      run: |
          mkdir -p circt/build
          cd circt/build
          wget https://github.com/llvm/circt/releases/download/firtool-1.36.0/circt-bin-ubuntu-20.04.tar.gz
          tar -xvf circt-bin-ubuntu-20.04.tar.gz
          export PATH=$PWD/firtool-1.36.0/bin:$PATH
          which circt-opt
          cd ../..
          sudo apt install -y verilator libgmp-dev libmpfr-dev libmpc-dev
          pip install -e git+https://github.com/phanrahan/magma.git#egg=magma-lang
          pip install -e git+https://github.com/phanrahan/mantle.git#egg=mantle
          pip install -e git+https://github.com/leonardt/mantle2.git#egg=mantle2

          pip install pytest pytest-pycodestyle
          pip install -e .
          pytest --pycodestyle tests/ riscv_mini/
