// Generated by CIRCT circtorg-0.0.0-1018-g3a39b339f
module aggregate_mux_wrapper(
  input  struct packed {logic [7:0] x; logic y; } a,
  input                                           s,
  output struct packed {logic [7:0] x; logic y; } y);

  struct packed {logic [7:0] x; logic y; } _GEN;
  always_comb begin
    if (~s)
      _GEN = '{x: (~a.x), y: (~a.y)};
    else if (s)
      _GEN = a;
  end // always_comb
  assign y = _GEN;
endmodule

