// Generated by CIRCT circtorg-0.0.0-658-g0d82b4bb2
module aggregate_mux_wrapper(	// <stdin>:1:1
  input  struct packed {logic [7:0] x; logic y; } a,
  input                                           s,
  output struct packed {logic [7:0] x; logic y; } y);

  wire struct packed {logic [7:0] x; logic y; }      _GEN = '{x: (~a.x), y: (~a.y)};	// <stdin>:2:10, :4:10, :5:10, :7:10, :8:10
  wire struct packed {logic [7:0] x; logic y; }[1:0] _GEN_0 = {{_GEN}, {a}};	// <stdin>:8:10, :9:10
  assign y = _GEN_0[s];	// <stdin>:9:10, :10:10, :11:5
endmodule

