// Generated by CIRCT circtorg-0.0.0-658-g0d82b4bb2
module non_power_of_two_mux_wrapper(	// <stdin>:1:1
  input  struct packed {logic [7:0] x; logic y; } a,
  input  [3:0]                                    s,
  output struct packed {logic [7:0] x; logic y; } y);

  wire struct packed {logic [7:0] x; logic y; }       _GEN = '{x: (~a.x), y: (~a.y)};	// <stdin>:2:10, :4:10, :5:10, :7:10, :8:10
  wire struct packed {logic [7:0] x; logic y; }       _GEN_0 = '{x: (~a.x), y: (~a.y)};	// <stdin>:2:10, :4:10, :5:10, :7:10, :9:10
  wire struct packed {logic [7:0] x; logic y; }       _GEN_1 = '{x: (~a.x), y: (~a.y)};	// <stdin>:2:10, :4:10, :5:10, :7:10, :10:10
  wire struct packed {logic [7:0] x; logic y; }       _GEN_2 = '{x: (~a.x), y: (~a.y)};	// <stdin>:2:10, :4:10, :5:10, :7:10, :11:10
  wire struct packed {logic [7:0] x; logic y; }       _GEN_3 = '{x: (~a.x), y: (~a.y)};	// <stdin>:2:10, :4:10, :5:10, :7:10, :12:11
  wire struct packed {logic [7:0] x; logic y; }       _GEN_4 = '{x: (~a.x), y: (~a.y)};	// <stdin>:2:10, :4:10, :5:10, :7:10, :13:11
  wire struct packed {logic [7:0] x; logic y; }       _GEN_5 = '{x: (~a.x), y: (~a.y)};	// <stdin>:2:10, :4:10, :5:10, :7:10, :14:11
  wire struct packed {logic [7:0] x; logic y; }       _GEN_6 = '{x: (~a.x), y: (~a.y)};	// <stdin>:2:10, :4:10, :5:10, :7:10, :15:11
  wire struct packed {logic [7:0] x; logic y; }       _GEN_7 = '{x: (~a.x), y: (~a.y)};	// <stdin>:2:10, :4:10, :5:10, :7:10, :16:11
  wire struct packed {logic [7:0] x; logic y; }       _GEN_8 = '{x: (~a.x), y: (~a.y)};	// <stdin>:2:10, :4:10, :5:10, :7:10, :17:11
  wire struct packed {logic [7:0] x; logic y; }       _GEN_9 = '{x: (~a.x), y: (~a.y)};	// <stdin>:2:10, :4:10, :5:10, :7:10, :18:11
  wire struct packed {logic [7:0] x; logic y; }[11:0] _GEN_10 = {{_GEN_9}, {_GEN_8}, {_GEN_7}, {_GEN_6}, {_GEN_5}, {_GEN_4}, {_GEN_3}, {_GEN_2}, {_GEN_1},
                {_GEN_0}, {_GEN}, {a}};	// <stdin>:8:10, :9:10, :10:10, :11:10, :12:11, :13:11, :14:11, :15:11, :16:11, :17:11, :18:11, :19:11
  assign y = _GEN_10[s];	// <stdin>:19:11, :20:11, :21:5
endmodule

