// Generated by CIRCT circtorg-0.0.0-2220-ge81df61a7
// external module simple_decl

module simple_decl_external(
  input  I,
  output O
);

  simple_decl simple_decl_inst0 (
    .I (I),
    .O (O)
  );
endmodule

