// Generated by CIRCT circtorg-0.0.0-1018-g3a39b339f
module simple_disallow_local_variables(
  input  [1:0] x,
  input        s,
  output [1:0] O);

  reg        _GEN;
  reg        _GEN_0;
  reg        _GEN_1;
  reg        _GEN_2;
  wire [1:0] _GEN_3 = ~x;
  always_comb begin
    if (s) begin
      _GEN = _GEN_3[0];
      _GEN_0 = _GEN_3[1];
    end
    else begin
      _GEN = x[0];
      _GEN_0 = x[1];
    end
    if (~s) begin
      _GEN_1 = _GEN_0;
      _GEN_2 = _GEN;
    end
    else begin
      _GEN_1 = _GEN;
      _GEN_2 = _GEN_0;
    end
  end // always_comb
  assign O = {_GEN_2, _GEN_1};
endmodule

