// Generated by CIRCT circtorg-0.0.0-1018-g3a39b339f
module simple_aggregates_nested_array(
  input  [7:0][3:0][15:0] a,
  output [7:0][3:0][15:0] y);

  assign y = {{a[3'h3]}, {a[3'h2]}, {a[3'h1]}, {a[3'h0]}, {a[3'h7]}, {a[3'h6]}, {a[3'h5]}, {a[3'h4]}};
endmodule

