// Generated by CIRCT circtorg-0.0.0-658-g0d82b4bb2
module simple_length_one_array(	// <stdin>:1:1
  input  [0:0][7:0] I,
  output [7:0]      O);

  assign O = I[1'h0];	// <stdin>:6:10, :7:5
endmodule

