// Generated by CIRCT circtorg-0.0.0-2220-ge81df61a7
module simple_aggregates_product(
  input  struct packed {logic [7:0] x; logic [7:0] y; } a,
  output struct packed {logic [7:0] x; logic [7:0] y; } y
);

  assign y = '{x: (~a.x), y: (~a.y)};
endmodule

