// Generated by CIRCT circtorg-0.0.0-1018-g3a39b339f
module proj_simple_comb(
  input  [15:0] a,
                b,
                c,
  output [15:0] y,
                z);

  assign y = 16'hFFFF;
  assign z = 16'hFFFF;
endmodule

