// Generated by CIRCT circtorg-0.0.0-1018-g3a39b339f
module simple_aggregates_array(
  input  [7:0][15:0] a,
  output [7:0][15:0] y,
  output [3:0][15:0] z);

  assign y = {a[3'h0 +: 4], a[3'h4 +: 4]};
  assign z = a[3'h0 +: 4];
endmodule

