// Generated by CIRCT circtorg-0.0.0-658-g0d82b4bb2
module LUT(
  input  [1:0] I,
  output [7:0] O);

  wire [3:0] _GEN = {{1'h1}, {1'h0}, {1'h1}, {1'h0}};
  wire [3:0] _GEN_0 = {{1'h1}, {1'h1}, {1'h0}, {1'h1}};
  wire [3:0] _GEN_1 = {{1'h1}, {1'h1}, {1'h1}, {1'h1}};
  wire [3:0] _GEN_2 = {{1'h1}, {1'h1}, {1'h1}, {1'h1}};
  wire [3:0] _GEN_3 = {{1'h0}, {1'h1}, {1'h0}, {1'h1}};
  wire [3:0] _GEN_4 = {{1'h1}, {1'h1}, {1'h1}, {1'h0}};
  wire [3:0] _GEN_5 = {{1'h1}, {1'h0}, {1'h0}, {1'h1}};
  wire [3:0] _GEN_6 = {{1'h1}, {1'h1}, {1'h1}, {1'h1}};
  assign O = {_GEN_6[I], _GEN_5[I], _GEN_4[I], _GEN_3[I], _GEN_2[I], _GEN_1[I], _GEN_0[I], _GEN[I]};
endmodule

module simple_lut(
  input  [1:0] a,
  output [7:0] y);

  LUT LUT_inst0 (
    .I (a),
    .O (y)
  );
endmodule

