// Generated by CIRCT circtorg-0.0.0-1773-g7abbc4313
module simple_comb(
  input  [15:0] a,
                b,
                c,
  output [15:0] y,
                z
);

  assign y = 16'hFFFF;
  assign z = 16'hFFFF;
endmodule

