// Generated by CIRCT circtorg-0.0.0-658-g0d82b4bb2
module simple_mux_wrapper(	// <stdin>:1:1
  input  [7:0] a,
  input        s,
  output [7:0] y);

  wire [1:0][7:0] _GEN = {{~a}, {a}};	// <stdin>:3:10, :4:10
  assign y = _GEN[s];	// <stdin>:4:10, :5:10, :6:5
endmodule

