// Generated by CIRCT circtorg-0.0.0-658-g0d82b4bb2
module simple_inline_verilog(	// <stdin>:1:1
  input  I,
  output O);

  
  	// This is 'a' "comment".	// <stdin>:3:5
  assign O = I;	// <stdin>:4:5
endmodule

