// Generated by CIRCT circtorg-0.0.0-2220-ge81df61a7
module no_outputs(
  input I
);

endmodule

module simple_side_effect_instance(
  input  I,
  output O
);

  no_outputs no_outputs_inst0 (
    .I (I)
  );
  assign O = I;
endmodule

