// Generated by CIRCT circtorg-0.0.0-658-g0d82b4bb2
module simple_wire(	// <stdin>:1:1
  input  [7:0] I,
  output [7:0] O);

  wire [7:0] tmp = I;	// <stdin>:2:10
  assign O = tmp;	// <stdin>:4:10, :5:5
endmodule

