// Generated by CIRCT circtorg-0.0.0-658-g0d82b4bb2
module simple_duplicate_symbols(	// <stdin>:1:1
  input        I,
  output [1:0] O);

  wire x = I;	// <stdin>:2:10
  wire x_0 = I;	// <stdin>:5:10
  assign O = {x_0, x};	// <stdin>:4:10, :7:10, :8:10, :9:5
endmodule

