// Generated by CIRCT circtorg-0.0.0-1018-g3a39b339f
module simple_comb(
  input  [15:0] a,
                b,
                c,
  output [15:0] y,
                z);

  assign y = 16'hFFFF;
  assign z = 16'hFFFF;
endmodule

module simple_undriven_instances();
  wire [15:0] _simple_comb_inst1_y;
  wire [15:0] _simple_comb_inst1_z;
  wire [15:0] _simple_comb_inst0_y;
  wire [15:0] _simple_comb_inst0_z;
  wire [15:0] _GEN;
  wire [15:0] _GEN_0;
  wire [15:0] _GEN_1;
  wire [15:0] _GEN_2;
  wire [15:0] _GEN_3;
  wire [15:0] _GEN_4;
  simple_comb simple_comb_inst0 (
    .a (_GEN),
    .b (_GEN_0),
    .c (_GEN_1),
    .y (_simple_comb_inst0_y),
    .z (_simple_comb_inst0_z)
  );
  simple_comb simple_comb_inst1 (
    .a (_GEN_2),
    .b (_GEN_3),
    .c (_GEN_4),
    .y (_simple_comb_inst1_y),
    .z (_simple_comb_inst1_z)
  );
endmodule

