// Generated by CIRCT circtorg-0.0.0-658-g0d82b4bb2
module simple_wrap_cast(	// <stdin>:1:1
  input  I,
  output O);

  wire coreir_wrapInClock_inst0 = I;	// <stdin>:2:10
  assign O = coreir_wrapInClock_inst0;	// <stdin>:4:10, :5:5
endmodule

