// Generated by CIRCT firtool-1.48.0-34-g7018fb13b
module tuple_key_ordering(
  input  struct packed {logic x; logic [7:0] y; } I,
  output struct packed {logic x; logic [7:0] y; } O
);

  assign O = I;
endmodule

