// Generated by CIRCT firtool-1.51.0-75-gbecb4c0ef
module tuple_key_ordering(
  input  struct packed {logic x; logic [7:0] y; } I,
  output struct packed {logic x; logic [7:0] y; } O
);

  assign O = I;
endmodule

