// Generated by CIRCT circtorg-0.0.0-658-g0d82b4bb2
module twizzler(	// <stdin>:1:1
  input  I0,
         I1,
         I2,
  output O0,
         O1,
         O2);

  assign O0 = ~I1;	// <stdin>:3:10, :6:5
  assign O1 = ~I0;	// <stdin>:4:10, :6:5
  assign O2 = ~I2;	// <stdin>:5:10, :6:5
endmodule

module twizzle(	// <stdin>:8:1
  input  I,
  output O);

  wire _t1_O0;	// <stdin>:10:18
  wire _t1_O1;	// <stdin>:10:18
  wire _t0_O0;	// <stdin>:9:18
  wire _t0_O1;	// <stdin>:9:18
  wire _t0_O2;	// <stdin>:9:18
  twizzler t0 (	// <stdin>:9:18
    .I0 (I),
    .I1 (_t1_O0),	// <stdin>:10:18
    .I2 (_t1_O1),	// <stdin>:10:18
    .O0 (_t0_O0),
    .O1 (_t0_O1),
    .O2 (_t0_O2)
  );
  twizzler t1 (	// <stdin>:10:18
    .I0 (_t0_O0),	// <stdin>:9:18
    .I1 (_t0_O1),	// <stdin>:9:18
    .I2 (_t0_O2),	// <stdin>:9:18
    .O0 (_t1_O0),
    .O1 (_t1_O1),
    .O2 (O)
  );
endmodule

