// Generated by CIRCT unknown git version
module test_when_nested_TupleBits2Bit(	// <stdin>:1:1
  input  struct packed {logic [1:0] _0; logic _1; }[1:0] I,
  input                                                  S,
  output struct packed {logic [1:0] _0; logic _1; }      O);

  reg [1:0] O0_reg;	// <stdin>:10:11
  reg       O1_reg;	// <stdin>:11:11

  always_comb begin	// <stdin>:12:5
    automatic struct packed {logic [1:0] _0; logic _1; } _GEN = I[1'h1];	// <stdin>:6:10, :7:10

    O0_reg = _GEN._0;	// <stdin>:8:10, :13:9
    O1_reg = _GEN._1;	// <stdin>:9:10, :14:9
    if (S) begin	// <stdin>:15:9
      automatic struct packed {logic [1:0] _0; logic _1; } _GEN_0 = I[1'h0];	// <stdin>:2:10, :3:10

      O0_reg = _GEN_0._0;	// <stdin>:4:10, :16:13
      O1_reg = _GEN_0._1;	// <stdin>:5:10, :17:13
    end
  end // always_comb
  assign O = '{_0: O0_reg, _1: O1_reg};	// <stdin>:20:10, :21:10, :22:11, :23:5
endmodule

