// Generated by CIRCT unknown git version
module test_when_with_default(	// <stdin>:1:1
  input  [1:0] I,
  input        S,
  output       O);

  reg O0_reg;	// <stdin>:4:10

  always_comb begin	// <stdin>:5:5
    O0_reg = I[1];	// <stdin>:3:10, :6:9
    if (S)	// <stdin>:7:9
      O0_reg = I[0];	// <stdin>:2:10, :8:13
  end // always_comb
  assign O = O0_reg;	// <stdin>:11:10, :12:5
endmodule

