// Generated by CIRCT unknown git version
module Foo(	// <stdin>:1:1
  input  struct packed {logic _0; logic [1:0] _1; }[1:0][1:0] I,
  input                                                       S,
  output struct packed {logic _0; logic [1:0] _1; }[1:0]      O);

  struct packed {logic _0; logic [1:0] _1; }[1:0] O0_reg;	// <stdin>:6:10

  always_comb begin	// <stdin>:7:5
    O0_reg = I[1'h1];	// <stdin>:4:10, :5:10, :8:9
    if (S)	// <stdin>:9:9
      O0_reg = I[1'h0];	// <stdin>:2:10, :3:10, :10:13
  end // always_comb
  assign O = O0_reg;	// <stdin>:13:10, :14:5
endmodule

