// Generated by CIRCT unknown git version
module Foo(	// <stdin>:1:1
  input  [2:0] I,
  input  [1:0] S,
  output       O);

  reg O0_reg;	// <stdin>:7:10

  always_comb begin	// <stdin>:8:5
    if (S[0])	// <stdin>:2:10, :9:9
      O0_reg = I[0];	// <stdin>:3:10, :10:13
    else if (S[1])	// <stdin>:2:10, :4:10, :9:9
      O0_reg = I[1];	// <stdin>:5:10, :13:17
    else	// <stdin>:2:10, :4:10, :9:9
      O0_reg = I[2];	// <stdin>:6:10, :15:17
  end // always_comb
  assign O = O0_reg;	// <stdin>:19:10, :20:5
endmodule

