// Generated by CIRCT unknown git version
module Foo(	// <stdin>:1:1
  input  [1:0] I,
               S,
  output       O);

  reg O0_reg;	// <stdin>:6:10

  always_comb begin	// <stdin>:7:5
    O0_reg = I[1];	// <stdin>:5:10, :8:9
    if (S[0]) begin	// <stdin>:2:10, :9:9
      if (S[1])	// <stdin>:3:10, :10:13
        O0_reg = I[0];	// <stdin>:4:10, :11:17
    end
  end // always_comb
  assign O = O0_reg;	// <stdin>:15:10, :16:5
endmodule

