// Generated by CIRCT unknown git version
// external module ConditionalDriversImpl

module Foo(	// <stdin>:2:1
  input  [1:0] I,
  input        S,
  output       O);

  reg O0_reg;	// <stdin>:5:10

  always_comb begin	// <stdin>:6:5
    O0_reg = I[1];	// <stdin>:4:10, :7:9
    if (S)	// <stdin>:8:9
      O0_reg = I[0];	// <stdin>:3:10, :9:13
  end // always_comb
  assign O = O0_reg;	// <stdin>:12:10, :13:5
endmodule

