// Generated by CIRCT unknown git version
module Foo(	// <stdin>:1:1
  input  [1:0] I,
               S,
  output       O0,
               O1);

  reg O0_reg;	// <stdin>:6:10
  reg O1_reg;	// <stdin>:7:10

  always_comb begin	// <stdin>:8:5
    O0_reg = I[1];	// <stdin>:5:10, :9:9
    O1_reg = I[0];	// <stdin>:4:10, :10:9
    if (S[0]) begin	// <stdin>:2:10, :11:9
      if (S[1]) begin	// <stdin>:3:10, :12:13
        O0_reg = I[0];	// <stdin>:4:10, :13:17
        O1_reg = I[1];	// <stdin>:5:10, :14:17
      end
    end
  end // always_comb
  assign O0 = O0_reg;	// <stdin>:18:10, :20:5
  assign O1 = O1_reg;	// <stdin>:19:10, :20:5
endmodule

