// Generated by CIRCT unknown git version
module test_wire_insertion_bad_verilog(
  input  [31:0] I,
  output        O);

  `ifdef LOGGING_ON
  wire _magma_inline_wire0 = I[0];
  $display("%x", _magma_inline_wire0);
  `endif LOGGING_ON
  assign O = _magma_inline_wire0;
endmodule

