// Generated by CIRCT firtool-1.51.0-75-gbecb4c0ef
module TopBasicAsserts_mlirverilog(
  input I,
        O,
        other
);

endmodule


bind Top TopBasicAsserts_mlirverilog TopBasicAsserts_mlirverilog_inst (
    .I(I),
    .O(O),
    .other(_magma_bind_wire_0)
);