// Generated by CIRCT firtool-1.48.0-34-g7018fb13b
module TopXMRAsserts_mlirverilog(
  input I,
        O,
        other
);

endmodule


bind Top TopXMRAsserts_mlirverilog TopXMRAsserts_mlirverilog_inst (
    .I(I),
    .O(O),
    .other(middle._magma_bind_wire_0)
);