// Generated by CIRCT firtool-1.48.0-34-g7018fb13b
// external module SB_DFF

module Top(
  input  C,
         D,
  output Q
);

  SB_DFF SB_DFF_inst0 (
    .C (C),
    .D (D),
    .Q (Q)
  );
endmodule

