// Generated by CIRCT firtool-1.48.0-34-g7018fb13b
// external module SB_CARRY

module Top(
  input  I0,
         I1,
         I2,
         CI,
  output CO
);

  SB_CARRY SB_CARRY_inst0 (
    .I0 (I0),
    .I1 (I1),
    .CI (CI),
    .CO (CO)
  );
endmodule

