// Generated by CIRCT firtool-1.48.0-34-g7018fb13b
// external module SB_PLL40_CORE

module SB_PLL(
  input  REFERENCECLK,
         RESETB,
         BYPASS,
  output PLLOUTCORE,
         PLLOUTGLOBAL
);

  SB_PLL40_CORE #(
    .FEEDBACK_PATH("SIMPLE"),
    .PLLOUT_SELECT("GENCLK"),
    .DIVR(0),
    .DIVF(63),
    .DIVQ(7),
    .FILTER_RANGE(1)
  ) SB_PLL40_CORE_inst0 (
    .REFERENCECLK (REFERENCECLK),
    .RESETB       (RESETB),
    .BYPASS       (BYPASS),
    .PLLOUTCORE   (PLLOUTCORE),
    .PLLOUTGLOBAL (PLLOUTGLOBAL)
  );
endmodule

module Top(
  input  REFERENCECLK,
         RESETB,
         BYPASS,
  output PLLOUTCORE,
         PLLOUTGLOBAL
);

  SB_PLL SB_PLL_inst0 (
    .REFERENCECLK (REFERENCECLK),
    .RESETB       (RESETB),
    .BYPASS       (BYPASS),
    .PLLOUTCORE   (PLLOUTCORE),
    .PLLOUTGLOBAL (PLLOUTGLOBAL)
  );
endmodule

