// Generated by CIRCT firtool-1.48.0-34-g7018fb13b
// external module SB_LUT4

module Top(
  input  I0,
         I1,
         I2,
         I3,
  output O
);

  SB_LUT4 #(
    .LUT_INIT(48879)
  ) SB_LUT4_inst0 (
    .I0 (I0),
    .I1 (I1),
    .I2 (I2),
    .I3 (I3),
    .O  (O)
  );
endmodule

