// Generated by CIRCT firtool-1.48.0-34-g7018fb13b
// external module SB_LUT4

// external module SB_CARRY

module LUT3(
  input  I0,
         I1,
         I2,
  output O
);

  SB_LUT4 #(
    .LUT_INIT(38550)
  ) SB_LUT4_inst0 (
    .I0 (I0),
    .I1 (I1),
    .I2 (I2),
    .I3 (1'h0),
    .O  (O)
  );
endmodule

module FullAdder(
  input  I0,
         I1,
         CIN,
  output O,
         COUT
);

  LUT3 LUT3_inst0 (
    .I0 (I0),
    .I1 (I1),
    .I2 (CIN),
    .O  (O)
  );
  SB_CARRY SB_CARRY_inst0 (
    .I0 (I0),
    .I1 (I1),
    .CI (CIN),
    .CO (COUT)
  );
endmodule

module Top(
  input  I0,
         I1,
         CIN,
  output O,
         COUT
);

  FullAdder FullAdder_inst0 (
    .I0   (I0),
    .I1   (I1),
    .CIN  (CIN),
    .O    (O),
    .COUT (COUT)
  );
endmodule

