// Generated by CIRCT firtool-1.48.0-34-g7018fb13b
// external module SB_LUT4

// external module SB_CARRY

module LUT2(
  input  I0,
         I1,
  output O
);

  SB_LUT4 #(
    .LUT_INIT(26214)
  ) SB_LUT4_inst0 (
    .I0 (I0),
    .I1 (I1),
    .I2 (1'h0),
    .I3 (1'h0),
    .O  (O)
  );
endmodule

module HalfAdder(
  input  I0,
         I1,
  output O,
         COUT
);

  LUT2 LUT2_inst0 (
    .I0 (I0),
    .I1 (I1),
    .O  (O)
  );
  SB_CARRY SB_CARRY_inst0 (
    .I0 (I0),
    .I1 (I1),
    .CI (1'h0),
    .CO (COUT)
  );
endmodule

module Top(
  input  I0,
         I1,
  output O,
         COUT
);

  HalfAdder HalfAdder_inst0 (
    .I0   (I0),
    .I1   (I1),
    .O    (O),
    .COUT (COUT)
  );
endmodule

