#!/bin/sh
ssh hanrahan@hanrahan-virtual-machine.local 'make -C build6 clean'
scp build/$1.v hanrahan@hanrahan-virtual-machine.local:~/build6/main.v
scp build/$1.ucf hanrahan@hanrahan-virtual-machine.local:~/build6/main.ucf
ssh hanrahan@hanrahan-virtual-machine.local 'make -C build6'
scp hanrahan@hanrahan-virtual-machine.local:~/build6/main.bit build/$1.bit

