// Generated by CIRCT unknown git version
module Foo(	// <stdin>:1:1
  input        I0_tag,
  input  [1:0] I0_data,
               I1,
  output       O0_tag,
  output [1:0] O0_data,
               O1,
  output       O2_tag,
  output [1:0] O2_data);

  reg Foo_O0_tag_reg;	// <stdin>:27:11
  reg Foo_O0_data5B05D_reg;	// <stdin>:28:11
  reg Foo_O0_data5B15D_reg;	// <stdin>:29:11
  reg Foo_O15B05D_reg;	// <stdin>:30:11
  reg Foo_O15B15D_reg;	// <stdin>:31:11
  reg Foo_O2_tag_reg;	// <stdin>:32:11
  reg Foo_O2_data5B05D_reg;	// <stdin>:33:11
  reg Foo_O2_data5B15D_reg;	// <stdin>:34:11

  always_comb begin	// <stdin>:35:5
    if (~I0_tag) begin	// <stdin>:3:10, :36:9
      Foo_O0_tag_reg = 1'h0;	// <stdin>:2:10, :37:13
      Foo_O0_data5B05D_reg = ~(I0_data[0]);	// <stdin>:5:10, :7:10, :38:13
      Foo_O0_data5B15D_reg = 1'h0;	// <stdin>:2:10, :39:13
      Foo_O15B05D_reg = I0_data[0];	// <stdin>:5:10, :40:13
      Foo_O15B15D_reg = 1'h0;	// <stdin>:2:10, :41:13
      Foo_O2_tag_reg = 1'h0;	// <stdin>:2:10, :42:13
      Foo_O2_data5B05D_reg = I1[1] ^ I1[0];	// <stdin>:10:10, :11:10, :12:11, :43:13
      Foo_O2_data5B15D_reg = 1'h0;	// <stdin>:2:10, :44:13
    end
    else begin	// <stdin>:3:10, :36:9
      automatic logic [1:0] _GEN = ~I0_data;	// <stdin>:15:11

      Foo_O0_tag_reg = 1'h1;	// <stdin>:6:10, :46:13
      Foo_O0_data5B05D_reg = _GEN[0];	// <stdin>:16:11, :47:13
      Foo_O0_data5B15D_reg = _GEN[1];	// <stdin>:17:11, :48:13
      Foo_O15B05D_reg = I0_data[0];	// <stdin>:20:11, :49:13
      Foo_O15B15D_reg = 1'h0;	// <stdin>:2:10, :50:13
      Foo_O2_tag_reg = 1'h1;	// <stdin>:6:10, :51:13
      Foo_O2_data5B05D_reg = I1[0];	// <stdin>:25:11, :52:13
      Foo_O2_data5B15D_reg = 1'h1;	// <stdin>:6:10, :53:13
    end
  end // always_comb
  assign O0_tag = Foo_O0_tag_reg;	// <stdin>:56:11, :67:5
  assign O0_data = {Foo_O0_data5B15D_reg, Foo_O0_data5B05D_reg};	// <stdin>:57:11, :58:11, :64:11, :67:5
  assign O1 = {Foo_O15B15D_reg, Foo_O15B05D_reg};	// <stdin>:59:11, :60:11, :65:11, :67:5
  assign O2_tag = Foo_O2_tag_reg;	// <stdin>:61:11, :67:5
  assign O2_data = {Foo_O2_data5B15D_reg, Foo_O2_data5B05D_reg};	// <stdin>:62:11, :63:11, :66:11, :67:5
endmodule

