// Generated by CIRCT unknown git version
module Foo(	// <stdin>:1:1
  input        I_tag,
  input  [1:0] I_data,
  output       O_tag,
  output [1:0] O_data);

  reg Foo_O_tag_reg;	// <stdin>:16:11
  reg Foo_O_data5B05D_reg;	// <stdin>:17:11
  reg Foo_O_data5B15D_reg;	// <stdin>:18:11

  always_comb begin	// <stdin>:19:5
    if (~I_tag) begin	// <stdin>:3:10, :20:9
      Foo_O_tag_reg = 1'h0;	// <stdin>:2:10, :21:13
      Foo_O_data5B05D_reg = ~(I_data[0]);	// <stdin>:5:10, :7:10, :22:13
      Foo_O_data5B15D_reg = 1'h0;	// <stdin>:2:10, :23:13
    end
    else begin	// <stdin>:3:10, :20:9
      Foo_O_tag_reg = 1'h1;	// <stdin>:6:10, :25:13
      Foo_O_data5B05D_reg = I_data[0];	// <stdin>:14:11, :26:13
      Foo_O_data5B15D_reg = I_data[1];	// <stdin>:15:11, :27:13
    end
  end // always_comb
  assign O_tag = Foo_O_tag_reg;	// <stdin>:30:11, :34:5
  assign O_data = {Foo_O_data5B15D_reg, Foo_O_data5B05D_reg};	// <stdin>:31:11, :32:11, :33:11, :34:5
endmodule

